language: go

matrix:
  include:
  - go: "1.10.x"
    script:
        - go get ./...
        - go build
        - go test -v ./...
  - go: "1.11.x"
    script:
        - go build
        - go test -v -mod=vendor ./...

env:
  - GO111MODULE=on

install: true